version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES:DB= myEcommerce
      - POSTGRES_USER:DB= esteban
      - POSTGRES_PASSWORD:DB= 1234
    ports:
      - 5433:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=1234
    ports:
      - 5050:80
